---
# tasks file for ansible
- name: copy src.txt as dest.txt in the same dir
  copy:
    src: /tmp/test.sh
    dest: /tmp/test.sh
  tags:
    - simple_copy

- name: check the physical memory
  shell: sh -x /tmp/test.sh
  register: phy_mem

- debug:
        var: phy_mem.stdout_lines

